services:
- docker
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  on: heroku_deploy
  app: probot-hamzaalalach
  api_key:
    secure: UQXzMDQ6Vc8kiqrgz3GLEXAXxly298Z6HLPJdX/XVm+9nrTbnYKPXerMyGhkBdFPJ1u6UeO461Gm6ntrmKEFMSJYGO7zEjHBF1FsC8DlucvstSyKung56bZgFkL1W6alayQybHAil+HYUBu35m64mVf0YK/1Ql1CFfAe208tCdAVEUUetVHcK4aGFFF2E74RlDX4miHUBigJzCrPaJ94vCZ6bCtt1USuR4wB8V8YVMTG6jWPYuemIyB3Ud0DJe4GuxMRc+NJQFO7ORVSFl2UWd1XbgIr6yDjn10TK6e+Ljoh1svpGssELr80BtWEt0m7wFcDMSWRGdmHzHnJ18VwIDPTeUu1JCVcZA6gzRGPseNPoltYWIYd471Cn4wqb8nnVIqazFXtja+9b0pK9Z139lYyHKCmx/uBfSOLJrDIKvKNrL0OjLplmRUcQZGOM2pOXF2GzHcJpVQT1qp6e9NjCLluCrnuZ2SklcoK+8mJpe7zuDCkyBDwSwnJpEIISEImbf7S8U0GUUkSkcIBEBQSU53DSy+q35nPiAY68726fNEodgfmadhPBK1NRRG3rOYsJs8PwAsMkrI4xf6OI1l9x/ES44tY17vrQLBlY5nVx3iNvP1RLUdTXZedc7yButE1PoBGRQ+b3I9IoUy2h10PdKFCdki7dsLKdIwySrxnHT8=
